export const TENANCY_ERRORS = {
  CODIGO_INVALID: 'TENANCY.CODIGO_INVALID',
  CODIGO_RESERVED: 'TENANCY.CODIGO_RESERVED',
  CODIGO_ALREADY_EXISTS: 'TENANCY.CODIGO_ALREADY_EXISTS',
  NOME_INVALID: 'TENANCY.NOME_INVALID',
  STATUS_INVALID: 'TENANCY.STATUS_INVALID',
  BANCA_NOT_FOUND: 'TENANCY.BANCA_NOT_FOUND',
} as const;

export type TenancyErrorCode = (typeof TENANCY_ERRORS)[keyof typeof TENANCY_ERRORS];
