/** Tokens de injeção para os contratos de domínio e portas do Participants. */
export const PARTY_REPOSITORY = 'PARTICIPANTS_PARTY_REPOSITORY';
export const BETTING_AGENT_REPOSITORY = 'PARTICIPANTS_BETTING_AGENT_REPOSITORY';
export const PARTY_DUPLICATE_QUERY = 'PARTICIPANTS_PARTY_DUPLICATE_QUERY';
export const BETTING_AGENT_QUERY = 'PARTICIPANTS_BETTING_AGENT_QUERY';
export const PERMISSION_CHECKER = 'PARTICIPANTS_PERMISSION_CHECKER';
export const CLOCK = 'PARTICIPANTS_CLOCK';
export const TRANSACTION_MANAGER = 'PARTICIPANTS_TRANSACTION_MANAGER';

/** Casos de uso compostos e injetados prontos no controller. */
export const CREATE_BETTING_AGENT_USE_CASE =
  'PARTICIPANTS_CREATE_BETTING_AGENT_USE_CASE';
export const LIST_BETTING_AGENTS_USE_CASE =
  'PARTICIPANTS_LIST_BETTING_AGENTS_USE_CASE';
export const GET_BETTING_AGENT_USE_CASE =
  'PARTICIPANTS_GET_BETTING_AGENT_USE_CASE';
export const UPDATE_BETTING_AGENT_PROFILE_USE_CASE =
  'PARTICIPANTS_UPDATE_BETTING_AGENT_PROFILE_USE_CASE';
export const SET_BETTING_AGENT_STATUS_USE_CASE =
  'PARTICIPANTS_SET_BETTING_AGENT_STATUS_USE_CASE';
