export const PARTICIPANTS_ERRORS = {
  FORBIDDEN: 'PARTICIPANTS.FORBIDDEN',
  CODE_ALREADY_EXISTS: 'PARTICIPANTS.CODE_ALREADY_EXISTS',
  POSSIBLE_DUPLICATE: 'PARTICIPANTS.POSSIBLE_DUPLICATE',
  BETTING_AGENT_NOT_FOUND: 'PARTICIPANTS.BETTING_AGENT_NOT_FOUND',
  INVALID_POLICY: 'PARTICIPANTS.INVALID_POLICY',
  INVALID_ADDRESS: 'PARTICIPANTS.INVALID_ADDRESS',
  INVALID_CODE: 'PARTICIPANTS.INVALID_CODE',
  INVALID_PHONE: 'PARTICIPANTS.INVALID_PHONE',
  INVALID_STATUS: 'PARTICIPANTS.INVALID_STATUS',
  INVALID_PARTY_TYPE: 'PARTICIPANTS.INVALID_PARTY_TYPE',
  PARTY_ALREADY_HAS_AGENT: 'PARTICIPANTS.PARTY_ALREADY_HAS_AGENT',
} as const;

export type ParticipantsErrorCode =
  (typeof PARTICIPANTS_ERRORS)[keyof typeof PARTICIPANTS_ERRORS];
