// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma',
  migrations: {
    path: 'prisma/migrations',
    // ts-node (não tsx/esbuild): o seed bootstrap um NestJS ApplicationContext
    // real via ProvisionBancaUseCase, e o esbuild do tsx não emite
    // `design:paramtypes` (emitDecoratorMetadata), quebrando a injeção de
    // dependência por tipo (JwtService, ConfigService, Reflector).
    seed: 'npx ts-node --transpile-only prisma/seed/main.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
