/** Tokens de injeção para os contratos de domínio e portas do Identity. */
export const USER_ACCOUNT_REPOSITORY = 'IDENTITY_USER_ACCOUNT_REPOSITORY';
export const SESSION_REPOSITORY = 'IDENTITY_SESSION_REPOSITORY';
export const PASSWORD_CRYPTO_PROVIDER = 'IDENTITY_PASSWORD_CRYPTO_PROVIDER';
export const ACCESS_TOKEN_ISSUER = 'IDENTITY_ACCESS_TOKEN_ISSUER';
export const REFRESH_TOKEN_GENERATOR = 'IDENTITY_REFRESH_TOKEN_GENERATOR';
export const REFRESH_TOKEN_DIGESTER = 'IDENTITY_REFRESH_TOKEN_DIGESTER';
export const TEMPORARY_PASSWORD_GENERATOR =
  'IDENTITY_TEMPORARY_PASSWORD_GENERATOR';
export const CLOCK = 'IDENTITY_CLOCK';
export const TRANSACTION_MANAGER = 'IDENTITY_TRANSACTION_MANAGER';
export const BANCA_CONTEXT_RESOLVER = 'IDENTITY_BANCA_CONTEXT_RESOLVER';
export const BANCA_DISPLAY_CONTEXT_RESOLVER =
  'IDENTITY_BANCA_DISPLAY_CONTEXT_RESOLVER';
export const AUTHENTICATED_USER_ACCOUNT_QUERY =
  'IDENTITY_AUTHENTICATED_USER_ACCOUNT_QUERY';
export const PERMISSION_CHECKER = 'IDENTITY_PERMISSION_CHECKER';
export const LIST_USER_ACCOUNTS_QUERY = 'IDENTITY_LIST_USER_ACCOUNTS_QUERY';

/** Casos de uso compostos e injetados prontos no controller. */
export const LOGIN_USE_CASE = 'IDENTITY_LOGIN_USE_CASE';
export const REFRESH_SESSION_USE_CASE = 'IDENTITY_REFRESH_SESSION_USE_CASE';
export const LOGOUT_USE_CASE = 'IDENTITY_LOGOUT_USE_CASE';
export const LOGOUT_ALL_USE_CASE = 'IDENTITY_LOGOUT_ALL_USE_CASE';
export const LIST_SESSIONS_USE_CASE = 'IDENTITY_LIST_SESSIONS_USE_CASE';
export const REVOKE_SESSION_USE_CASE = 'IDENTITY_REVOKE_SESSION_USE_CASE';
export const CHANGE_PASSWORD_USE_CASE = 'IDENTITY_CHANGE_PASSWORD_USE_CASE';
export const MANDATORY_PASSWORD_CHANGE_USE_CASE =
  'IDENTITY_MANDATORY_PASSWORD_CHANGE_USE_CASE';
export const ADMIN_RESET_PASSWORD_USE_CASE =
  'IDENTITY_ADMIN_RESET_PASSWORD_USE_CASE';
export const TOGGLE_ACCOUNT_STATUS_USE_CASE =
  'IDENTITY_TOGGLE_ACCOUNT_STATUS_USE_CASE';
export const CREATE_USER_ACCOUNT_USE_CASE =
  'IDENTITY_CREATE_USER_ACCOUNT_USE_CASE';
export const GET_AUTHENTICATED_USER_CONTEXT_USE_CASE =
  'IDENTITY_GET_AUTHENTICATED_USER_CONTEXT_USE_CASE';
export const UPDATE_OWN_PROFILE_USE_CASE =
  'IDENTITY_UPDATE_OWN_PROFILE_USE_CASE';
export const LIST_USER_ACCOUNTS_USE_CASE =
  'IDENTITY_LIST_USER_ACCOUNTS_USE_CASE';
export const GET_USER_ACCOUNT_USE_CASE = 'IDENTITY_GET_USER_ACCOUNT_USE_CASE';
export const UPDATE_USER_ACCOUNT_USE_CASE =
  'IDENTITY_UPDATE_USER_ACCOUNT_USE_CASE';
export const CHANGE_ACCOUNT_ROLE_USE_CASE =
  'IDENTITY_CHANGE_ACCOUNT_ROLE_USE_CASE';
export const ADMIN_LIST_ACCOUNT_SESSIONS_USE_CASE =
  'IDENTITY_ADMIN_LIST_ACCOUNT_SESSIONS_USE_CASE';
export const ADMIN_REVOKE_ACCOUNT_SESSION_USE_CASE =
  'IDENTITY_ADMIN_REVOKE_ACCOUNT_SESSION_USE_CASE';
export const ADMIN_CREATE_USER_ACCOUNT_USE_CASE =
  'IDENTITY_ADMIN_CREATE_USER_ACCOUNT_USE_CASE';
