export const IDENTITY_ERRORS = {
  USERNAME_ALREADY_EXISTS: 'IDENTITY.USERNAME_ALREADY_EXISTS',
  ACCOUNT_NOT_FOUND: 'IDENTITY.ACCOUNT_NOT_FOUND',
  ACCOUNT_LOCKED: 'IDENTITY.ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'IDENTITY.ACCOUNT_INACTIVE',
  INVALID_CREDENTIALS: 'IDENTITY.INVALID_CREDENTIALS',
  SESSION_NOT_FOUND: 'IDENTITY.SESSION_NOT_FOUND',
  SESSION_REVOKED: 'IDENTITY.SESSION_REVOKED',
  MUST_CHANGE_PASSWORD: 'IDENTITY.MUST_CHANGE_PASSWORD',
  BANCA_NOT_FOUND: 'IDENTITY.BANCA_NOT_FOUND',
  BANCA_INACTIVE: 'IDENTITY.BANCA_INACTIVE',
  FORBIDDEN: 'IDENTITY.FORBIDDEN',
  PASSWORD_TOO_WEAK: 'IDENTITY.PASSWORD_TOO_WEAK',
  INVALID_FAILED_LOGIN_ATTEMPTS: 'IDENTITY.INVALID_FAILED_LOGIN_ATTEMPTS',
  INVALID_SESSION_EXPIRATION: 'IDENTITY.INVALID_SESSION_EXPIRATION',
  CONCURRENCY_CONFLICT: 'IDENTITY.CONCURRENCY_CONFLICT',
  CURRENT_PASSWORD_INCORRECT: 'IDENTITY.CURRENT_PASSWORD_INCORRECT',
  TARGET_SESSION_NOT_FOUND: 'IDENTITY.TARGET_SESSION_NOT_FOUND',
} as const;

export type IdentityErrorCode = (typeof IDENTITY_ERRORS)[keyof typeof IDENTITY_ERRORS];
