/** Tokens de injeção para os casos de uso de Access Control. */
export const GET_ROLE_PERMISSION_MATRIX_USE_CASE =
  'ACCESS_CONTROL_GET_ROLE_PERMISSION_MATRIX_USE_CASE';
export const GET_OWN_EFFECTIVE_PERMISSIONS_USE_CASE =
  'ACCESS_CONTROL_GET_OWN_EFFECTIVE_PERMISSIONS_USE_CASE';
