export const ACCESS_CONTROL_ERRORS = {
  UNKNOWN_PERMISSION_KEY: 'ACCESS_CONTROL.UNKNOWN_PERMISSION_KEY',
  FORBIDDEN: 'ACCESS_CONTROL.FORBIDDEN',
} as const;

export type AccessControlErrorCode =
  (typeof ACCESS_CONTROL_ERRORS)[keyof typeof ACCESS_CONTROL_ERRORS];
